Algoritmo "Calculo"

Var
   maior, menor: Real

Inicio
   Escreva("Digite um número: ")
   Leia(maior)
   Escreva("Digite outro número: ")
   Leia(menor)

   Se maior > menor Então
       Escreva("O primeiro número é maior que o segundo.")
   Senao Se maior < menor Então
       Escreva("O segundo número é maior que o primeiro.")
   Senão
       Escreva("Os números são iguais.")
   FimSe

Fimalgoritmo
